services:
  identifier:
    ports:
      - "80:80"
  frontend:
    environment:
      EMBER_ENV: "development"
  triplestore:
    ports:
      - "8890:8890"
  dcat-validator:
    environment:
      MODE: "development"
  catalog-harvester:
    environment:
      MODE: "development"
