x-logging: 
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.11.0
    environment:
      SESSION_COOKIE_SECURE: "on"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  dispatcher:
    image: semtech/mu-dispatcher:2.1.1
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  frontend:
    image: redpencil/frontend-dcat-validator:1.1.0-integration.1
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  # Your extra services here

  validation-api:
    image: redpencil/validation-api-service:1.1.0-V3_0_0-support.1
    labels:
      - "logging=true"
    environment:
      DEFAULT_MU_AUTH_SCOPE: 'http://services.semantic.works/validation-api/create-job'
    restart: always
    logging: *default-logging

  dcat-validator:
    image: redpencil/dcat-validator-service:1.1.0-integration.2
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  catalog-harvester:
    image: redpencil/catalog-harvester-service:feature-rdf-fallback-for-xml
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  job-controller:
    image: lblod/job-controller-service:1.2.0
    volumes:
      - ./config/job-controller/:/config/
    environment:
      LOG_SPARQL_QUERIES: "true"
      LOG_SPARQL_UPDATES: "true"
    restart: always
    logging: *default-logging

  resource:
    image: semtech/mu-cl-resources:1.27.2
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  migrations:
    image: semtech/mu-migrations-service:0.9.0
    links:
      - triplestore:database
    environment:
      MU_SPARQL_TIMEOUT: 600
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  delta-notifier:
    image: nvdk/mu-delta-notifier:1.1.0
    volumes:
      - ./config/delta:/config/
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  database:
    image: semtech/sparql-parser:0.0.15
    volumes:
      - ./config/authorization/:/config/
      - ./data/authorization/:/data/
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  triplestore:
    image: redpencil/virtuoso:1.3.0
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
